version: '3'
services:
  qdrant:
    image: qdrant/qdrant:v2.0.0
    container_name: qdrant
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  qdrant_data:
    driver: local
